# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rdec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 11, 13, 19, 44, 358000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
