# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-05 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, help_text='Required. 254 characters or fewer. Valid e-mail addresses only.', max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
